title = "documango"
description = "Turn a directory of Markdown files into a documentation website."

[[links]]
title = "GitHub"
url = "https://github.com/desertthunder/documango"

[fonts]
body = "Plus Jakarta Sans"
mono = "Google Sans Code"
